# Rapidmail example config.
rapidmail:
    api_username_hash: 'XXXXXXX'
    api_password_hash: 'XXXXXXX'
    campaigns:
        dailyNewsletterCampagin:
            list_id: '123456' # Id of your newsletter list.
